services:
### source: https://github.com/streamthoughts/kafka-monitoring-stack-docker-compose/blob/master/kraft-single-node-stack.yml
  kafka:
      image: confluentinc/cp-kafka:latest
      ports:
        - "9092:9092"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: 'broker,controller' # In KRaft, a node can be a Broker (handles data), a Controller (manages the cluster), or both. Here, this single node does both.
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
        KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9094,PLAINTEXT_HOST://localhost:9092'
  
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        CLUSTER_ID: 'MkU3OEVBNTcwNTJDRkU2Qf' # A random unique ID for the cluster
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  
  producer-packets-app: ### suppose to run Dockerfile_producer_packets_app to run
    build: 
      context: .
      dockerfile: Dockerfile_producer_packets_app
    cap_add:
      - NET_ADMIN # We need NET_ADMIN capability to allow the app to capture packets
      - NET_RAW # We need NET_RAW capability to allow the app to capture packets
    network_mode: "host" # We need to use host networking to allow the app to connect to Kafka on localhost
    depends_on:
      - kafka
    volumes:
      - ./k8s/config-map.yaml:/app/k8s/config-map.yaml

  packet-app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./k8s/config-map.yaml:/app/k8s/config-map.yaml
      - .:/app 
