apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: packet-pipeline
data:
  config.yaml: |
    bootstrap_servers_local: "localhost:9092"
    bootstrap_servers: "kafka:9094"
    source_topic: "raw_packets"
    consumer_group_id: "packet-consumer-group"

    transformed_topic: "sorted_packets"
    packets_stream_interface: "LAN2"
    consumer_group_id_transformed_packets: "transformed_packets_consumer_group"

    window_size_sec: 10
